# Generated by Django 5.2 on 2025-04-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=255)),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
                ('is_booked', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.screening')),
            ],
        ),
    ]
